Update chromium.arm.SlackBuild.diff

diff --git a/chromium/chromium.arm.SlackBuild.diff b/chromium/chromium.arm.SlackBuild.diff
--- a/chromium/chromium.arm.SlackBuild.diff
+++ b/chromium/chromium.arm.SlackBuild.diff
@@ -1,5 +1,5 @@
 --- chromium.SlackBuild.orig	2021-09-14 23:57:16.000000000 +0200
-+++ chromium.SlackBuild	2021-10-12 14:37:17.903371086 +0200
++++ chromium.SlackBuild	2021-10-12 18:31:58.649198061 +0200
 @@ -21,11 +21,14 @@
  #   OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
  #   SUCH DAMAGE.
@@ -16,7 +16,12 @@
  # For:             chromium
  # Descr:           Open Source version of Chrome Web Browser
  # URL:             http://www.chromium.org/
-@@ -37,391 +40,63 @@
+@@ -33,395 +36,71 @@
+ #                  - nodejs >= 15.6.0;
+ #                  - gcc >= 8 for bootstrapping gn;
+ #                  - nasm >= 2.14 (yasm no longer being used);
++#                    or llvm/clang 13 >=;
+ #                  - cmake >= 3.13.4;
  #                  - python3 >= 3.7, python3-setuptools;
  #                  - java runtime
  #                  - Internet access (for downloading toolchain bins)
@@ -436,6 +441,9 @@
 +#                  * cleared changelog history as its kind of irrelevant and old...
 +# 94.0.4606.81-1:  12/oct/2021 by Minime <slackware[at]slackwarelinux[dot]se>
 +#                  * Update to M94.
++#                  * Needs llvm/clang 13, so system clang is no longer an option.
++#                  * Will build with python 3.9, but if upgraded to python 3.10
++#                    there will be issues. Need to revert package python 3.10 to 3.9. 
 +#
  # -----------------------------------------------------------------------------
 -# 
@@ -450,7 +458,7 @@
  #
  # -----------------------------------------------------------------------------
  
-@@ -438,10 +113,10 @@
+@@ -438,10 +117,10 @@
  
  SRCNAM=chromium
  PRGNAM=${SRCNAM}${SRCEXT}     # chromium, chromium-dev, chromium-ungoogled, etc
@@ -464,7 +472,7 @@
  
  # Cross-compiling 32bit binaries on 64bit Slackware; set to "YES":
  CROSS32=${CROSS32:-"NO"}
-@@ -502,14 +177,16 @@
+@@ -502,14 +181,16 @@
  # clang for download0:
  USE_CLANG=${USE_CLANG:-1}
  
@@ -484,12 +492,31 @@
 +# Make sure you to set correct clang base path.
 +# Path where you installed clang, default is set to "/usr" (The system).
 +# If you installed my llvm/clang package then set CLANG_BASE_PATH="/opt/llvm".
-+#CLANG_BASE_PATH="/opt/llvm"
-+CLANG_BASE_PATH="/usr"
++#CLANG_BASE_PATH="/usr"
++CLANG_BASE_PATH="/opt/llvm"
  
  # If you don't want to enable support for Widevine CDM
  # (content decryption module) say "0" here.
-@@ -543,7 +220,7 @@
+@@ -533,6 +214,18 @@
+ PKG=$TMP/package-$PRGNAM
+ OUTPUT=${OUTPUT:-/tmp}
+ 
++if [ ! -f "${CLANG_BASE_PATH}/bin/clang" ]; then
++  echo "You have not installed llvm/clang"
++  echo "Build will fail"
++  exit 1
++else
++  CLANG_MIN=13
++  if [ ! $(${CLANG_BASE_PATH}/bin/clang --version |grep '^clang' |cut -d' ' -f3 |cut -d. -f1) -ge ${CLANG_MIN} ]; then
++    echo "Need newer version of llvm/clang"
++    exit 1
++  fi
++fi
++
+ # Visible directory listing of anything Chrome related is:
+ #   http://gsdview.appspot.com/
+ # Official location (non-browsable) of the above is:
+@@ -543,7 +236,7 @@
  # If you rebuild this package, you can use your own API keys. See:
  #   http://www.chromium.org/developers/how-tos/api-keys
  # This browser is now compiled without API keys. This will disable stuff like
@@ -498,7 +525,7 @@
  # The following variables must be set to access Google's public APIs:
  #   _google_api_key
  #   _google_default_client_id
-@@ -587,7 +264,8 @@
+@@ -587,7 +280,8 @@
  if [ -z "$ARCH" ]; then
    case "$MARCH" in
      i?86)    export ARCH=i586 ;;
@@ -508,7 +535,7 @@
      arm*)    export ARCH=arm ;;
      # Unless $ARCH is already set, use uname -m for all other archs:
      *)       export ARCH=$MARCH ;;
-@@ -623,7 +301,21 @@
+@@ -623,7 +317,21 @@
               #DSSE="0"
               DSSE="1"
               ;;
@@ -531,7 +558,7 @@
               SLKLDFLAGS="-Wl,-z,notext"; LIBDIRSUFFIX=""
               DSSE="1"
               # Widevine not supported (no binary library available):
-@@ -650,9 +342,8 @@
+@@ -650,9 +358,8 @@
  esac
  
  case "$ARCH" in
@@ -542,7 +569,7 @@
  esac
  
  # Exit the script on errors:
-@@ -759,6 +450,40 @@
+@@ -759,6 +466,40 @@
  # Be compatible with gcc 10:
  cat $SRCDIR/patches/chromium_gcc10.patch | patch -p1 --verbose \
    2>&1 | tee -a $OUTPUT/patch-${PRGNAM}.log
@@ -583,7 +610,7 @@
  # Fix the link on 32bit:
  sed -e '/ldflags /s/-m32/&", "-Wl,-z,notext/' \
    -i build/config/compiler/BUILD.gn
-@@ -812,15 +537,16 @@
+@@ -812,15 +553,16 @@
  # And fix the 32bit compilation while we are at it:
  sed -i tools/clang/scripts/build.py -e "s/ldflags = \[\]/ldflags = \['-latomic'\]/"
  
@@ -606,7 +633,7 @@
  fi
  
  # When compiling google's clang, use the system cmake
-@@ -857,19 +583,20 @@
+@@ -857,19 +599,20 @@
  fi
  
  chown -R root:root .
@@ -630,7 +657,7 @@
  
  export LDFLAGS="$SLKLDFLAGS"
  export CXXFLAGS="$SLKCFLAGS -Wno-unknown-warning-option"
-@@ -887,32 +614,26 @@
+@@ -887,32 +630,26 @@
      'enable_mse_mpeg2ts_stream_parser=true'
      'enable_precompiled_headers=false'
      'enable_swiftshader=true'
@@ -666,7 +693,7 @@
      'use_kerberos=false'
      'use_lld=true'
      'use_ozone=true'
-@@ -923,32 +644,50 @@
+@@ -923,32 +660,50 @@
      "extra_cxxflags=\"${CXXFLAGS}\""
      "extra_ldflags=\"${LDFLAGS}\""
  )
@@ -733,7 +760,7 @@
  # Add Google API key if defined:
  if [ -n "$_google_api_key" ]; then
    _chromium_conf+=(
-@@ -1064,10 +803,8 @@
+@@ -1064,10 +819,8 @@
      build/linux/${SYSROOTDIR}/usr/lib/${SYSROOT_TARGET}/libsqlite3.so
  
    # The platform-specific alias for the ARM readelf binary is missing
@@ -746,7 +773,7 @@
    fi
  fi
  
-@@ -1085,23 +822,9 @@
+@@ -1085,23 +838,9 @@
  ulimit -n 2048
  
  # Compile google's internal clang sources if needed
@@ -771,7 +798,7 @@
    LDFLAGS="$LDFLAGS" \
    python3 tools/clang/scripts/build.py \
      --bootstrap \
-@@ -1116,7 +839,11 @@
+@@ -1116,7 +855,11 @@
  
    # Ensure that only this new clang is used, ignoring the system version:
    MYCLANG_PATH="$TMP/tmp-$PRGNAM/${SRCNAM}-${VERSION}/third_party/llvm-build/Release+Asserts/bin"
@@ -784,7 +811,7 @@
  fi
  
  # For Chromium 92, disable ffmpeg re-configuration on 32bit OS,
-@@ -1137,7 +864,7 @@
+@@ -1137,7 +880,7 @@
    fi
    cd third_party/ffmpeg
      ## To prevent error on x86_64:
@@ -793,7 +820,7 @@
      ## in third_party/ffmpeg/build.x64.linux/ChromeOS/ffbuild/config.log
      #sed -e "s/--extra-ldflags=-fuse-ld=lld/--extra-ldflags=''/" \
      #    -i chromium/scripts/build_ffmpeg.py
-@@ -1156,24 +883,21 @@
+@@ -1156,24 +899,21 @@
  # Generate the ninja build files:
  echo "-- Bootstrapping 'gn'."
  
@@ -827,7 +854,7 @@
    fi
  fi
  
-@@ -1184,20 +908,20 @@
+@@ -1184,20 +924,20 @@
  # Compile everything:
  echo "-- Compiling the lot."
  
@@ -855,7 +882,7 @@
  fi
  export AS=as
  export AR=ar
-@@ -1324,6 +1048,13 @@
+@@ -1324,6 +1064,13 @@
  # Add a desktop file:
  process_template chrome/installer/linux/common/desktop.template \
    out/Release/${PRGNAM}.desktop
@@ -869,7 +896,7 @@
  install -D -m0644 out/Release/${PRGNAM}.desktop \
    $PKG/usr/share/applications/${PRGNAM}.desktop
  
-@@ -1466,5 +1197,10 @@
+@@ -1466,5 +1213,10 @@
  cd -
  cat $PKG/install/slack-desc | grep "^${PRGNAM}" > $OUTPUT/${PRGNAM}-${VERSION}-${PKGARCH}-${BUILD}${TAG}.txt
  
