Update chromium.SlackBuild.diff
Now, as I finally manage to get chromium 154.0.8037.92 to compile we have synced this to AlienBob's chromium 154.0.8037.97 build

diff --git a/chromium/chromium.SlackBuild.diff b/chromium/chromium.SlackBuild.diff
--- a/chromium/chromium.SlackBuild.diff
+++ b/chromium/chromium.SlackBuild.diff
@@ -1,8 +1,8 @@
---- chromium.SlackBuild.154.orig	2026-09-30 17:23:08.000000000 +0200
-+++ chromium.SlackBuild.154	2026-10-04 18:43:02.292364036 +0200
+--- chromium.SlackBuild.154.97.orig	2026-10-03 12:00:38.000000000 +0200
++++ chromium.SlackBuild	2026-10-04 21:32:02.523361076 +0200
 @@ -1,5 +1,5 @@
  #!/bin/bash
--# $Id: chromium.SlackBuild,v 1.596 2026/09/30 15:23:01 root Exp root $
+-# $Id: chromium.SlackBuild,v 1.597 2026/10/03 10:00:32 root Exp root $
 +# $Id: chromium.SlackBuild,v 1.586 2026/09/11 18:59:32 root Exp root $
  # Copyright 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026  Eric Hameleers, Eindhoven, NL
  # All rights reserved.
@@ -75,7 +75,7 @@
  #                   * Update.
  # 151.0.7922.137-1: 12/aug/2026 by Eric Hameleers <alien@slackware.com>
  #                   * Update.
-@@ -144,16 +161,22 @@
+@@ -144,18 +161,26 @@
  #                   * Update to M153.
  # 153.0.8010.52-1:  18/sep/2026 by Eric Hameleers <alien@slackware.com>
  #                   * Update.
@@ -85,8 +85,12 @@
  #                   * Update to M154.
  # 154.0.8037.92-1:  30/sep/2026 by Eric Hameleers <alien@slackware.com>
  #                   * Update.
--# 
 +#                   03/oct/2026 by Minime <slackware[at]slackwarelinux[dot]se>
++#                   * Fixed build for AArch64
+ # 154.0.8037.97-1:  03/oct/2026 by Eric Hameleers <alien@slackware.com>
+ #                   * Update.
+-# 
++#                   04/oct/2026 by Minime <slackware[at]slackwarelinux[dot]se>
 +#                   * Fixed build for AArch64
 +#
 +
@@ -101,16 +105,16 @@
  #
  # -----------------------------------------------------------------------------
  
-@@ -173,7 +196,7 @@
- VERSION=${VERSION:-154.0.8037.92}
- UNGOOGLED=${UNGOOGLED:-154.0.8037.92-1}
+@@ -175,7 +200,7 @@
+ VERSION=${VERSION:-154.0.8037.97}
+ UNGOOGLED=${UNGOOGLED:-154.0.8037.97-1}
  BUILD=${BUILD:-1}
 -TAG=${TAG:-alien}
 +TAG=${TAG:-SLse}
  
  # It's recommended to build 32bit binaries in a 32bit chroot on a 64bit OS.
  # Cross-compiling 32bit binaries on 64bit Slackware; set to "YES":
-@@ -298,7 +321,7 @@
+@@ -300,7 +325,7 @@
  GNBIN=${GNBIN:-/usr/local/bin/gn}
  
  # Slackware branding:
@@ -119,7 +123,7 @@
  
  # Where do we look for sources?
  SRCDIR=$(cd $(dirname $0); pwd)
-@@ -318,7 +341,7 @@
+@@ -320,7 +345,7 @@
  # If you rebuild this package, you can use your own API keys. See:
  #   http://www.chromium.org/developers/how-tos/api-keys
  # This browser is now compiled without API keys. This will disable stuff like
@@ -128,7 +132,7 @@
  # The following variables must be set to access Google's public APIs:
  #   _google_api_key
  #   _google_default_client_id
-@@ -452,7 +475,14 @@
+@@ -454,7 +479,14 @@
  
  # Source locations:
  SOURCE[0]="$SRCDIR/${SRCNAM}-${VERSION}.tar.xz"
@@ -144,7 +148,7 @@
  
  SOURCE[1]="$SRCDIR/widevine-versions.txt"
  SRCURL[1]="https://dl.google.com/widevine-cdm/versions.txt"
-@@ -542,10 +572,14 @@
+@@ -544,10 +576,14 @@
  # Patches and bug fixes:
  touch $OUTPUT/patch-${PRGNAM}.log
  # Arch contributions:
@@ -163,7 +167,7 @@
  echo "-- chromium147_revert-clang-no-lifetime-dse-flag.patch --"
  cat $SRCDIR/patches/chromium147_revert-clang-no-lifetime-dse-flag.patch \
    | patch -p1 --verbose \
-@@ -567,6 +601,10 @@
+@@ -569,6 +605,10 @@
    | patch -p1 --verbose \
    2>&1 | tee -a $OUTPUT/patch-${PRGNAM}.log
  # NixOS contributions:
@@ -174,7 +178,7 @@
  # Debian contributions:
  echo "-- chromium149_bytemuck.patch --"
  cat $SRCDIR/patches/chromium149_bytemuck.patch \
-@@ -598,22 +636,9 @@
+@@ -600,22 +640,9 @@
    | patch -p1 --verbose \
    2>&1 | tee -a $OUTPUT/patch-${PRGNAM}.log
  # Ungoogled contributions:
@@ -198,7 +202,7 @@
  # the future import right above the first actual module import:
  sed -i ./tools/metrics/histograms/extract_histograms.py \
    -e "/^import bisect/i from __future__ import annotations\n"
-@@ -631,9 +656,9 @@
+@@ -633,9 +660,9 @@
  
  if [ ${USE_CLANG} -eq 1 ] && [ ${BUILD_CLANG} -eq 0 ]; then
    # Adjust expectations about where to find the clang libs on Slackware:
@@ -211,7 +215,7 @@
    echo "-- compiler-rt-adjust-paths.patch --"
    cat $SRCDIR/patches/compiler-rt-adjust-paths.patch | patch -p1 --verbose \
      2>&1 | tee -a $OUTPUT/patch-${PRGNAM}.log
-@@ -850,6 +875,86 @@
+@@ -852,6 +879,91 @@
  sed -i BUILD.gn \
    -e 's/target_os != "linux" || /target_os == "linux" || /'
  
@@ -248,6 +252,11 @@
 +  rm -f third_party/typescript/linux-amd64/src/lib/tsc
 +  ln -s ../../../../devtools-frontend/src/node_modules/@typescript/tsc/bin/tsc \
 +    third_party/typescript/linux-amd64/src/lib/tsc
++
++  if ! third_party/typescript/linux-amd64/src/lib/tsc --version | grep -q 'Version 6.0.2'; then
++    echo "ERROR: Chromium TypeScript 6.0.2 was not found!"
++    exit 1
++  fi
 +
 +  # Allow TypeScript compiler library definitions from the ARM64 compiler installation.
 +  sed -i "/'third_party\/node\/node_modules\/',/a\    'third_party/devtools-frontend/src/node_modules/@typescript/tsc/lib/'," \
@@ -298,7 +307,7 @@
  # Prevent a build failure (yes, 'x64' even on 32bit Slackware):
  mkdir -p third_party/node/linux/node-linux-x64/bin
  # In case a binary is already there:
-@@ -932,7 +1037,7 @@
+@@ -934,7 +1046,7 @@
      'blink_symbol_level=0'
      "enable_hevc_parser_and_hw_decoder=${do_hevc}"
      "enable_platform_hevc=${do_hevc}"
@@ -307,7 +316,7 @@
      "enable_platform_ac3_eac3_audio=${do_hevc}"
      "enable_platform_dolby_vision=${do_hevc}"
      'enable_platform_mpeg_h_audio=true'
-@@ -954,7 +1059,7 @@
+@@ -956,7 +1068,7 @@
      "ozone_platform_wayland=${do_wayland}"
      #"rtc_use_pipewire=${do_wayland}"
      #"rtc_link_pipewire=${do_wayland}"
@@ -316,7 +325,7 @@
      'proprietary_codecs=true'
      'remove_webcore_debug_symbols=true'
      'symbol_level=0'
-@@ -1233,6 +1338,9 @@
+@@ -1235,6 +1347,9 @@
      #--host-cc /usr/bin/clang \
      #--host-cxx /usr/bin/clang++ \
  
@@ -326,7 +335,7 @@
    # Building gn for Chromium 110 fails when this file is not present:
    if [ ! -f third_party/llvm-build/Release+Asserts/cr_build_revision ]; then
      CLANG_REVISION=$(grep ^CLANG_REVISION tools/clang/scripts/update.py |cut -d= -f2 |tr -d " '")
-@@ -1351,7 +1459,7 @@
+@@ -1353,7 +1468,7 @@
    fi
    cd third_party/ffmpeg
      ## To prevent error on x86_64:
@@ -335,7 +344,7 @@
      ## in third_party/ffmpeg/build.x64.linux/ChromeOS/ffbuild/config.log
      #sed -e "s/--extra-ldflags=-fuse-ld=lld/--extra-ldflags=''/" \
      #    -i chromium/scripts/build_ffmpeg.py
-@@ -1388,7 +1496,8 @@
+@@ -1390,7 +1505,8 @@
  
  # Generate the ninja build files:
  
@@ -345,7 +354,7 @@
    echo "-- Bootstrapping 'gn'."
  
    if [ "${GOOGLE_CLANG}" == "src" ] && [  ${BUILD_CLANG} -eq 1 ]; then
-@@ -1397,11 +1506,47 @@
+@@ -1399,11 +1515,47 @@
    fi
  
    if [ -e tools/gn/build/gen.py ]; then
@@ -398,7 +407,7 @@
    else
      # Download and build the latest:
      git clone https://gn.googlesource.com/gn gn.git
-@@ -1416,6 +1561,7 @@
+@@ -1418,6 +1570,7 @@
      popd
      install -m0755 -D -t out/Release gn.git/out/gn
    fi
@@ -406,7 +415,7 @@
  else
     mkdir -p out/Release
     ln -s ${GNBIN} out/Release/
-@@ -1435,10 +1581,10 @@
+@@ -1437,10 +1590,10 @@
  
  if [ ${USE_CLANG} -eq 1 ] && [ ${BUILD_CLANG} -eq 0 ]; then
    # Use system toolchain:
@@ -419,7 +428,7 @@
    mkdir -p third_party/rust-toolchain/bin
    ln -s /usr/bin/rustc third_party/rust-toolchain/bin/rustc
  
-@@ -1470,9 +1616,15 @@
+@@ -1472,9 +1625,15 @@
  fi
  
  # Dawn needs our system go:
@@ -438,7 +447,7 @@
  
  echo "-- Generating ninja build files."
  out/Release/gn gen out/Release -v --args="${_chromium_conf[*]}" \
-@@ -1572,9 +1724,9 @@
+@@ -1574,9 +1733,9 @@
  # Install appdata:
  # This file provides the 'process_template' function:
  if [ -f chrome/installer/linux/common/installer.include ]; then
@@ -450,26 +459,7 @@
  fi
  source chrome/installer/linux/common/chromium-browser.info 
  
-@@ -1651,6 +1803,18 @@
- install -D -m0644 out/Release/${PRGNAM}.desktop \
-   $PKG/usr/share/applications/${PRGNAM}.desktop
- 
-+# Fix user-agent for aarch64
-+# Not needed any more as latest libwidevinecdm format has changed
-+#if [ "$ARCH" == "aarch64" ]; then
-+#  MAJOR_VER="$(echo ${VERSION} | cut -d. -f1)"
-+#  cp out/Release/${PRGNAM}.desktop out/Release/${PRGNAM}-netflix.desktop
-+#  sed -i out/Release/${PRGNAM}-netflix.desktop \
-+#    -e "s/Name\=Chromium-ungoogled Web Browser/Name\=Chromium-ungoogled Netflix/" \
-+#    -e "s/\/${PRGNAM}/\/${PRGNAM} \-\-user-agent=\"Mozilla\/5.0 \(X11; CrOS ${ARCH} 10895.56.0\) AppleWebKit\/537.36 \(KHTML, like Gecko\) Chrome\/${MAJOR_VER}.0.0.0 Safari\/537.36\"/"
-+#  install -D -m0644 out/Release/${PRGNAM}-netflix.desktop \
-+#    $PKG/usr/share/applications/${PRGNAM}-netflix.desktop
-+#fi
-+
- # Install desktop icons:
- for size in 16 32; do
-   install -D -m0644 \
-@@ -1798,5 +1962,12 @@
+@@ -1800,5 +1959,12 @@
  cd -
  cat $PKG/install/slack-desc | grep "^${PRGNAM}" > $OUTPUT/${PRGNAM}-${VERSION}-${PKGARCH}-${BUILD}${TAG}.txt
  
